// <auto-generated />
using System;
using ApiWkTechnology.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiWkTechnology.Infra.Migrations
{
    [DbContext(typeof(WkTechnologyContext))]
    [Migration("20220504232607_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiWkTechnology.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aa6c1d0-0eb4-4dae-8813-08d9e2b4aa87"),
                            Descricao = "Categoria reservada para panelas e utensílios da cozinha",
                            Nome = "Utensílios de cozinha"
                        },
                        new
                        {
                            Id = new Guid("03e68c0c-1164-43c9-6bb9-08d9e34472ad"),
                            Descricao = "Categoria reservada para móveis e produtos de decoração",
                            Nome = "Móveis"
                        },
                        new
                        {
                            Id = new Guid("69881eb1-b47e-4d56-6bc1-08d9e34472ad"),
                            Descricao = "Categoria reservada para equipamentos eletrônicos",
                            Nome = "Peças de informática"
                        });
                });

            modelBuilder.Entity("ApiWkTechnology.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93f1dc21-f381-46ff-0990-08d9e28b76b2"),
                            CategoriaId = new Guid("5aa6c1d0-0eb4-4dae-8813-08d9e2b4aa87"),
                            Descricao = "Panela de Pressão aço reforçado, Cor: Preta",
                            Marca = "INOX",
                            Nome = "Panela de Pressão",
                            Preco = 29.989999999999998
                        },
                        new
                        {
                            Id = new Guid("d68e04a3-0612-4034-098e-08d9e28b76b2"),
                            CategoriaId = new Guid("5aa6c1d0-0eb4-4dae-8813-08d9e2b4aa87"),
                            Descricao = "Frigideira anti-aderente, Cor: Azul",
                            Marca = "INOX",
                            Nome = "Frigideira",
                            Preco = 19.5
                        },
                        new
                        {
                            Id = new Guid("c4edecaa-0ca1-4113-098f-08d9e28b76b2"),
                            CategoriaId = new Guid("5aa6c1d0-0eb4-4dae-8813-08d9e2b4aa87"),
                            Descricao = "Liquidificador, Cor: Branco",
                            Marca = "Britânia",
                            Nome = "Liquidificador",
                            Preco = 89.25
                        },
                        new
                        {
                            Id = new Guid("f80244ce-8a53-4d00-8810-08d9e2b4aa87"),
                            CategoriaId = new Guid("03e68c0c-1164-43c9-6bb9-08d9e34472ad"),
                            Descricao = "Poltrona Inclinável 90°, Cor: Preta",
                            Marca = "Ortobom",
                            Nome = "Poltrona",
                            Preco = 299.99000000000001
                        },
                        new
                        {
                            Id = new Guid("6da8a2ce-5eeb-4adf-8811-08d9e2b4aa87"),
                            CategoriaId = new Guid("03e68c0c-1164-43c9-6bb9-08d9e34472ad"),
                            Descricao = "Sofá 3 lugares, Cor: Preta",
                            Marca = "Orthoflex",
                            Nome = "Sofá",
                            Preco = 910.0
                        },
                        new
                        {
                            Id = new Guid("d61bcb30-ed4f-4dc0-8812-08d9e2b4aa87"),
                            CategoriaId = new Guid("03e68c0c-1164-43c9-6bb9-08d9e34472ad"),
                            Descricao = "Mesa de Janta 8 lugares",
                            Marca = "Madereira Selva",
                            Nome = "Mesa",
                            Preco = 1200.0
                        },
                        new
                        {
                            Id = new Guid("5aa6c1d0-0eb4-4dae-8813-08d9e2b4aa87"),
                            CategoriaId = new Guid("69881eb1-b47e-4d56-6bc1-08d9e34472ad"),
                            Descricao = "Memória ram 8GB 2400MHZ",
                            Marca = "HyperX",
                            Nome = "Memória 8GB",
                            Preco = 199.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a086f9b0-fac6-4301-3854-08d9e2c206fe"),
                            CategoriaId = new Guid("69881eb1-b47e-4d56-6bc1-08d9e34472ad"),
                            Descricao = "Monitor 144 Hz , 0.5 ms IPS",
                            Marca = "ACE",
                            Nome = "Monitor 144",
                            Preco = 1500.0
                        },
                        new
                        {
                            Id = new Guid("f7bdc102-84e9-41f7-3855-08d9e2c206fe"),
                            CategoriaId = new Guid("69881eb1-b47e-4d56-6bc1-08d9e34472ad"),
                            Descricao = "Monitor UltraWide 29 polegadas, 75 Hz , 5 ms",
                            Marca = "LG",
                            Nome = "UltraWide 29",
                            Preco = 1299.99
                        });
                });

            modelBuilder.Entity("ApiWkTechnology.Domain.Entities.Produto", b =>
                {
                    b.HasOne("ApiWkTechnology.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ApiWkTechnology.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
